### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by zhren711** [linjing7/VR-Baseline#15]
Hi,linjing. Thank you very much for the open source code. Unfortunately, I'm meeting some problems while running your code. I used the pre-trained model to test on my dataset, with  the  command `python demo/restoration_video_demo.py configs/FGST_deblur_dvd_test.py pretrained_models/FGST/FGST_dvd.pth data/test.mp4 data/`, but I got the following Error Message
`RuntimeError: CUDA out of memory. Tried to allocate 2.97 GiB (GPU 0; 11.77 GiB total capacity; 8.25 GiB already allocated; 420.50 MiB free; 9.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
My GPU is one Nvidia Geforce rtx3080ti 12G. So, can I do this test on an existing GPU?

**Comment by linjing7** [comment]
Hi, you can set `cpu_cache_length` in this [line](https://github.com/linjing7/VR-Baseline/blob/0ba4f0075a709a64bdce8c73ecf51ebf0e453182/mmedit/models/backbones/sr_backbones/FGST.py#L29) into a smaller number. In this way, the temp feature will be saved in the CPU.

**Comment by wgp666** [comment]
> Hi, you can set `cpu_cache_length` in this [line](https://github.com/linjing7/VR-Baseline/blob/0ba4f0075a709a64bdce8c73ecf51ebf0e453182/mmedit/models/backbones/sr_backbones/FGST.py#L29) into a smaller number. In this way, the temp feature will be saved in the CPU.

Hello! I also have this problem when testing on the DVD dataset using the pre-trained model via the command `bash tools/dist_train.sh configs/FGST_deblur_dvd_test.py`.  I have set `cpu_cache_length` to 1, but I still get the following error `RuntimeError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 3; 23.70 GiB total capacity; 11.35 GiB already allocated; 19.56 MiB free; 11.48 GiB reserved in total by PyTorch)`. My GPU is an Nvidia Geforce rtx3090 24G. Is there any other solution?

**Comment by linjing7** [comment]
Hi, you can try to split the image into patches and then test by setting `patch_test=True` in this [line](https://github.com/linjing7/VR-Baseline/blob/0ba4f0075a709a64bdce8c73ecf51ebf0e453182/mmedit/models/backbones/sr_backbones/FGST.py#L29). The result would be slightly influenced, but I think it would greatly save the memory.

**Comment by wgp666** [comment]
> Hi, you can try to split the image into patches and then test by setting `patch_test=True` in this [line](https://github.com/linjing7/VR-Baseline/blob/0ba4f0075a709a64bdce8c73ecf51ebf0e453182/mmedit/models/backbones/sr_backbones/FGST.py#L29). The result would be slightly influenced, but I think it would greatly save the memory.

I have set `cpu_cache_length` to 0 and `patch_test` to `True`, but I still get the following error. Is there any other solution?
/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/torch/nn/functional.py:3829: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "/home/user/VR-Baseline-main/tools/train.py", line 169, in <module>
    main()
  File "/home/user/VR-Baseline-main/tools/train.py", line 165, in main
    meta=meta)
  File "/home/user/VR-Baseline-main/mmedit/apis/train.py", line 112, in train_model
    meta=meta)
  File "/home/user/VR-Baseline-main/mmedit/apis/train.py", line 361, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/user/VR-Baseline-main/mmedit/models/restorers/basicvsr.py", line 103, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/VR-Baseline-main/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/home/user/VR-Baseline-main/mmedit/models/restorers/basic_restorer.py", line 90, in forward_train
    output = self.generator(lq)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/VR-Baseline-main/mmedit/models/backbones/sr_backbones/FGST.py", line 197, in forward
    feats['encoder2'] = self.encoder_2(feats['encoder2'], flows['forward_ds2'], flows['backward_ds2'], self.cpu_cache)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/VR-Baseline-main/mmedit/models/backbones/sr_backbones/FGST_util.py", line 288, in forward
    video = layer(video, flows_forward=flows_forward, flows_backward=flows_backward, cpu_cache=cpu_cache)
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/VR-Baseline-main/mmedit/models/backbones/sr_backbones/FGST_util.py", line 246, in forward
    out = self.attn(q_inp=q_inp, k_inp=k_inp, flow=[flow_f,flow_b]) + q_inp
  File "/home/user/anaconda3/envs/VR/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/VR-Baseline-main/mmedit/models/backbones/sr_backbones/FGST_util.py", line 118, in forward
    q_inp, k_inp = map(lambda x: torch.roll(x, shifts=(-hb//2, -wb//2), dims=(-2, -1)), (q_inp, k_inp))
  File "/home/user/VR-Baseline-main/mmedit/models/backbones/sr_backbones/FGST_util.py", line 118, in <lambda>
    q_inp, k_inp = map(lambda x: torch.roll(x, shifts=(-hb//2, -wb//2), dims=(-2, -1)), (q_inp, k_inp))
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 23.70 GiB total capacity; 17.19 GiB already allocated; 19.56 MiB free; 17.31 GiB reserved in total by PyTorch)

**Comment by linjing7** [comment]
Hi, I have never tested the model with RTX3090, but I remember that I could test with 32G V100. I'll test on RTX3090 in these two days and tell you the solution.

**Comment by wgp666** [comment]
> Hi, I have never tested the model with RTX3090, but I remember that I could test with 32G V100. I'll test on RTX3090 in these two days and tell you the solution.

"Okay, thank you for your answer!"

**Comment by linjing7** [comment]
Hi, I'm sorry that FGST could only be tested with a device with at least 30G memory. But you can test each video separately by running `python demo/restoration_video_demo.py configs/FGST_deblur_gopro_test.py ./pretrained_model/FGST_gopro.pth INPUT_VIDEO.mp4 OUTPUT_VIDEO.mp4`. This can be done in the RTX3090.

**Comment by zhren711** [comment]
It seems that the resolution will have to be reduced to achieve training in my machine , but it is not acceptable for super resolution. Anyway , thanks for your answers.
