### ISSUE TITLE
About S2SVR model

### ISSUE THREAD

**Issue by Xiao-R-Y** [linjing7/VR-Baseline#22]
Thanks for your excellent work, I would like to know whether the S2SVR model is provided, after config the environment with your guidance and run the command **bash tools/dist_train.sh configs/S2SVR_sr_reds4.py 8**

I met a problem :**KeyError: "BasicVSR: 'S2SVR is not in the model registry'"**

logs are as follows

Traceback (most recent call last):
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/sdb/xiaorunyu/xry/video_SR/S2S/VR-Baseline/mmedit/models/restorers/basicvsr.py", line 41, in __init__
    pretrained)
  File "/mnt/sdb/xiaorunyu/xry/video_SR/S2S/VR-Baseline/mmedit/models/restorers/basic_restorer.py", line 48, in __init__
    self.generator = build_backbone(generator)
  File "/mnt/sdb/xiaorunyu/xry/video_SR/S2S/VR-Baseline/mmedit/models/builder.py", line 31, in build_backbone
    return build(cfg, BACKBONES)
  File "/mnt/sdb/xiaorunyu/xry/video_SR/S2S/VR-Baseline/mmedit/models/builder.py", line 22, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'S2SVR is not in the model registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 169, in <module>
    main()
  File "tools/train.py", line 133, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/mnt/sdb/xiaorunyu/xry/video_SR/S2S/VR-Baseline/mmedit/models/builder.py", line 60, in build_model
    return build(cfg, MODELS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/mnt/sdb/xiaorunyu/xry/video_SR/S2S/VR-Baseline/mmedit/models/builder.py", line 22, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "BasicVSR: 'S2SVR is not in the model registry'"
Killing subprocess 922430
Traceback (most recent call last):
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/zhangyang/envs/anaconda3/envs/video/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhangyang/envs/anaconda3/envs/video/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/S2SVR_sr_reds4.py', '--seed', '0', '--launcher', 'pytorch']' returned non-zero exit status 1.

If you could give me any instructions? Thank you.

**Comment by linjing7** [comment]
Hi, did you install the environments following our instructions? Besides, could you successfully run FGST?
